catalogues:
  designmuseum:
    url: "https://data.designmuseumgent.be/"
    format: "json-ld"
  marineregions:
    url: "http://marineregions.org/dcat"
    format: "turtle"
  geomobility:
    url: "https://brugge-ldes.geomobility.eu/"
    format: "turtle"
  cogent:
    url: "https://apidg.gent.be/opendata/adlib2eventstream/v1/"
    format: "json-ld"