# Simple workflow for deploying static content to GitHub Pages
name: Validate a DCAT catalogue.

on:
  pull_request_target:
    branches:
      - 'main'
  push:
    branches:
      - 'onboarding/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build application
        run: make

